---
- name: UI REDEPLOY
  hosts: production
  gather_facts: false
  tags: ui
  tasks:
    - name: Copy src
      synchronize:
        src: "{{ playbook_dir }}/../../{{ ui_root }}/"
        dest: "{{ ui_root }}"
        delete: true
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=.idea"

#    - name: Setup nginx conf
#      become: true
#      template:
#        src: ./templates/my-nginx.conf
#        dest: ~/my-nginx.conf
#      notify: restart nginx
#
#  handlers:
#    - name: restart nginx
#      service:
#        name: nginx
#        state: restarted
#        args: -c ~/my-nginx.conf

  vars:
    ui_root: "bounch-quiz"
